server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product_team?serverTimezone=UTC&characterEncoding=UTF-8
    username: product
    password: product
    hikari:
      max-lifetime: 60_0000 # 10분
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3_000 # 3초

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      org:
        hibernate:
          format_sql: true
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://127.0.0.1:3306/product_team?serverTimezone=UTC&characterEncoding=UTF-8
    baseline-version: 1
    user: product
    password: product
    enabled: true
    locations: classpath:db/migration
    schemas: product_team

  kafka:
    endpoint:
      community: localhost:9092
    consumer:
      group:
        id: "product.consumer.local"