spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product_team_test?serverTimezone=UTC&characterEncoding=UTF-8
    username: product
    password: product
    hikari:
      max-lifetime: 60_0000 # 10분
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3_000 # 3초
  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://127.0.0.1:3306/product_team_test?serverTimezone=UTC&characterEncoding=UTF-8
    baseline-version: 1
    user: product
    password: product
    enabled: true
    locations: classpath:db/migration
    schemas: product_team_test
    clean-disabled: false

  jpa:
    hibernate:
      ddl-auto: create