CREATE DATABASE IF NOT EXISTS product_team DEFAULT CHARSET = utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS product_team_test DEFAULT CHARSET = utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'product'@'%' IDENTIFIED BY 'product';
GRANT ALL PRIVILEGES ON *.* TO 'product'@'%';
FLUSH PRIVILEGES;
;